PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# Modified code. Credit: https://www.wikidata.org/wiki/Wikidata:Request_a_query/Archive/2019/03#reach_ORCIDs_of_authors_via_PubMed-IDs_of_articles
SELECT DISTINCT ?item ?itemLabel ?orcid
WHERE {
  ?item rdfs:label|foaf:name|skos:altLabel "%s"@en .
  VALUES ?orcid { "%s" }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" .}
}